import com.github.spotbugs.snom.SpotBugsTask

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'checkstyle'
	id 'pmd'
	id("com.github.spotbugs") version "6.1.9"
}

group = 'king.leonidas'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

spotbugs {
	excludeFilter = file("$rootDir/config/spotbugs/exclude.xml")
}

pmd {
	consoleOutput = true
	toolVersion = "7.13.0"
	ruleSetFiles = files("$rootDir/config/pmd/quickstart.xml")
	rulesMinimumPriority = 5
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


	// https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
	implementation 'org.apache.commons:commons-collections4:4.5.0'

	//https://docs.gradle.org/current/userguide/checkstyle_plugin.html
	implementation 'com.puppycrawl.tools:checkstyle:10.23.0'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(SpotBugsTask).configureEach {
	reports {
		xml.required = false
		html.required = true // Enable HTML report
	}
}

tasks.withType(Pmd).configureEach {
	reports {
		xml.required.set(true)
		html.required.set(true) // Enables HTML reports
	}
}

