name: Inventory Continuous Integration

on:
    pull_request:
        branches: [dev]

jobs:
    tests:
        name: Integration Checks
        runs-on: ubuntu-latest

        steps:
            -   name: Check out code
                uses: actions/checkout@v4

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'
            
            -   name: Run Checkstyle
                uses: dbelyaev/action-checkstyle@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    reporter: github-pr-review
                    checkstyle_config: ./config/checkstyle/checkstyle.xml

            -   name: Run PMD
                uses: pmd/pmd-github-action@v2
                with:
                    rulesets: './config/pmd/quickstart.xml'

            -   name: Fail when there are PMD Violations
                if: steps.pmd.outputs.violations != 0
                run: exit 1

            -   name: Grant Execute Permission for GradleW
                run: chmod +x ./gradlew

            -   name: Run SpotBugs via Gradle
                run: ./gradlew spotbugsMain